spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: 123456
  url: jdbc:mysql://127.0.0.1:3306/mybatis-test?characterEncoding=UTF-8
server:
 port: 8081
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
